import type { AppSettings, Product } from "./types";

// Not: Statuslar açılışta computeProductStatus ile yeniden hesaplanır,
// burada yazılanlar yalnızca başlangıç tohumudur.
export const MOCK_PRODUCTS: Product[] = [
  {
    id: "p_macbook_air_m2",
    name: "MacBook Air M2",
    brand: "Apple",
    category: "Bilgisayar",
    store: "Hepsiburada",
    price: 42999,
    purchaseDate: "2025-11-12",
    warrantyEndDate: "2027-11-12",
    returnDeadline: "2025-11-26",
    invoiceNumber: "HB-2025-118842",
    trackingNumber: "ARS123456789",
    status: "active",
    notes: "Eğitim için alındı. Klavye TR-Q.",
    documents: [
      {
        id: "d_macbook_invoice",
        productId: "p_macbook_air_m2",
        name: "Hepsiburada Faturası.pdf",
        type: "invoice",
        date: "2025-11-12",
      },
      {
        id: "d_macbook_warranty",
        productId: "p_macbook_air_m2",
        name: "Apple Sınırlı Garanti.pdf",
        type: "warranty",
        date: "2025-11-12",
      },
    ],
    serviceRecords: [],
  },
  {
    id: "p_airpods_pro",
    name: "AirPods Pro",
    brand: "Apple",
    category: "Kulaklık",
    store: "Trendyol",
    price: 8999,
    purchaseDate: "2026-05-10",
    warrantyEndDate: "2028-05-10",
    returnDeadline: "2026-05-24",
    invoiceNumber: "TY-2026-552210",
    status: "active",
    notes: "Hediye için alındı.",
    documents: [
      {
        id: "d_airpods_invoice",
        productId: "p_airpods_pro",
        name: "Trendyol E-Faturası.pdf",
        type: "invoice",
        date: "2026-05-10",
      },
    ],
    serviceRecords: [],
  },
  {
    id: "p_philips_kahve",
    name: "Kahve Makinesi",
    brand: "Philips",
    category: "Küçük ev aleti",
    store: "MediaMarkt",
    price: 6499,
    purchaseDate: "2025-04-08",
    warrantyEndDate: "2027-04-08",
    returnDeadline: "2025-04-22",
    invoiceNumber: "MM-2025-31221",
    status: "in_service",
    notes: "Su deposu sızdırıyor, servis bekleniyor.",
    documents: [
      {
        id: "d_philips_invoice",
        productId: "p_philips_kahve",
        name: "MediaMarkt Faturası.pdf",
        type: "invoice",
        date: "2025-04-08",
      },
      {
        id: "d_philips_service",
        productId: "p_philips_kahve",
        name: "Servis Kabul Formu.pdf",
        type: "service_form",
        date: "2026-05-02",
      },
    ],
    serviceRecords: [
      {
        id: "s_philips_001",
        productId: "p_philips_kahve",
        date: "2026-05-02",
        company: "Philips Yetkili Servis - Kadıköy",
        description: "Su deposu sızdırma şikayeti, garanti kapsamında",
        status: "in_progress",
        hasServiceForm: true,
        nextFollowUpDate: "2026-05-25",
      },
    ],
  },
  {
    id: "p_samsung_watch",
    name: "Akıllı Saat",
    brand: "Samsung",
    category: "Giyilebilir teknoloji",
    store: "Amazon",
    price: 5999,
    purchaseDate: "2024-06-01",
    warrantyEndDate: "2026-06-01",
    returnDeadline: "2024-06-15",
    invoiceNumber: "AMZ-2024-71182",
    status: "warranty_expiring",
    documents: [
      {
        id: "d_samsung_invoice",
        productId: "p_samsung_watch",
        name: "Amazon Faturası.pdf",
        type: "invoice",
        date: "2024-06-01",
      },
    ],
    serviceRecords: [],
  },
];

export const DEFAULT_SETTINGS: AppSettings = {
  profileName: "Misafir Kullanıcı",
  notificationsEnabled: true,
  warrantyWarnDays: 30,
  returnWarnDays: 5,
  theme: "light",
};

export const CATEGORY_SUGGESTIONS = [
  "Bilgisayar",
  "Telefon",
  "Kulaklık",
  "Giyilebilir teknoloji",
  "Küçük ev aleti",
  "Beyaz eşya",
  "TV & Görüntü",
  "Oyun & Konsol",
  "Mobilya",
  "Giyim",
  "Diğer",
];

export const STORE_SUGGESTIONS = [
  "Trendyol",
  "Hepsiburada",
  "Amazon",
  "MediaMarkt",
  "Teknosa",
  "Vatan Bilgisayar",
  "n11",
  "Mağaza (Fiziki)",
  "Diğer",
];
